### ISSUE TITLE
Bug in Angular UI Bootstrap Pagination: Unexpected end of expression: selectPage(page

### ISSUE THREAD

**Issue by warrendodsworth** [angular/angularjs-batarang#234] opened 2015-07-03 11:32 UTC
While Batarang is Enabled and there is an Angular UI Bootstrap Pagination control on the page this error pops up in the console. 

It does not cause the pager to behave differently in my experience though, but vanishes when Batarang is disabled.

Error: [$parse:ueoe] Unexpected end of expression: selectPage(page
http://errors.angularjs.org/1.3.16/$parse/ueoe?p0=selectPage(page
    at REGEX_STRING_REGEXP (http://localhost:9000/bower_components/angular/angular.js:63:12)
    at Parser.consume (http://localhost:9000/bower_components/angular/angular.js:12151:13)
    at Parser.functionCall (http://localhost:9000/bower_components/angular/angular.js:12426:10)
    at Parser.primary (http://localhost:9000/bower_components/angular/angular.js:12098:24)
    at Parser.unary (http://localhost:9000/bower_components/angular/angular.js:12374:19)
    at Parser.multiplicative (http://localhost:9000/bower_components/angular/angular.js:12357:21)
    at Parser.additive (http://localhost:9000/bower_components/angular/angular.js:12348:21)
    at Parser.relational (http://localhost:9000/bower_components/angular/angular.js:12339:21)
    at Parser.equality (http://localhost:9000/bower_components/angular/angular.js:12330:21)
    at Parser.logicalAND (http://localhost:9000/bower_components/angular/angular.js:12321:21)

**Comment by SomeKittens** [comment] 2015-07-05 20:08
Can you paste the full expression (that starts with `selectPage(page`)?  This may be related to a few other bugs we've been having.

**Comment by warrendodsworth** [comment] 2015-07-06 01:09
Hey, the template is the default from Angular UI Pagination, I havent tried it with the pager. 

https://github.com/angular-ui/bootstrap/blob/master/template/pagination/pagination.html

Hope it helps. Nice plugin. Thanks.

**Comment by SomeKittens** [comment] 2015-07-06 01:59
Helps a lot.  This is a dupe of https://github.com/angular/angularjs-batarang/issues/230 (which we're working on).  Thanks!

**Closed by SomeKittens** 2015-07-06 01:59 UTC
