### ISSUE TITLE
Batarang chrome plugin doesn't work anymore?

### ISSUE THREAD

**Issue by rakeshjuyal** [angular/angularjs-batarang#207] opened 2015-01-22 01:31 UTC
Batarang chrome plugin used to work earlier. but now it have stopped working. I see nothing in Batarang dev tools tab. Looking at the plugins review, looks like it is broken for all.

**Comment by elvenking** [comment] 2015-01-22 13:43
Something really wrong happened with Batarang. It was a nice tool we used in our team.  It seems that manual downgrade will work.

**Comment by jhgg** [comment] 2015-01-22 15:58
For real. What happened to this? I got upgraded to 0.7.4 and EVERYTHING is gone!! 

![image](https://cloud.githubusercontent.com/assets/5489149/5859069/88f106e0-a225-11e4-96ab-f0865eed8bc2.png)

**Comment by divmgl** [comment] 2015-01-22 19:52
Same here... What's going on?

**Comment by rakeshjuyal** [comment] 2015-01-23 03:12
@elvenking I tried older version as well. Nothing worked.

**Comment by webmaxru** [comment] 2015-01-23 13:23
+1

**Comment by elvenking** [comment] 2015-01-23 14:54
@rakeshjuyal what about to try an older version of Chrome ?

**Comment by xylax11** [comment] 2015-01-23 19:30
0.4.3 Still works somewhat.

**Comment by rakeshjuyal** [comment] 2015-01-24 04:16
@elvenking I tried till 0.5 . It did not work.

**Comment by manikantag** [comment] 2015-01-25 20:18
+1. Borken :(

**Comment by zelk** [comment] 2015-01-26 10:39
+1 All functionality is gone!

**Comment by hanfeisun** [comment] 2015-01-26 10:45
Haven't you read this issue.. The author is asking for help

https://github.com/angular/angularjs-batarang/issues/194

**Comment by levithomason** [comment] 2015-02-23 23:00
There are 800+ of us using Batarang.  If you've enjoyed it's benefits and probably made some money using it over the years, please offer your time.  There are enough +1's and issues posted on the chrome store to know it's busted.

Let's do what the open source world does well, let's pull together and fix this thing for all our benefit.

**Comment by photusenigma** [comment] 2015-03-02 21:49
+1 @levithomason comment

**Comment by thomaspons** [comment] 2015-03-03 13:53
@levithomason I'm agree with you but a roadmap of fixes could be great to begin it ! Because i think that the matter is not just a simple patch of few lines. So if someone can give informations i believe that everyone else can repair this awesome tool :) !

**Comment by levithomason** [comment] 2015-03-18 14:40
Couple places to start looking would be #194 "I need your help!" and the current PRs.  Seems the goal is to get some e2e tests going, which is a great start.  See #197 "Protractor tests with multiple profiles".

If you know of a bug that needs fixed, have a look at [CONTRIBUTING.md](https://github.com/angular/angularjs-batarang/blob/master/CONTRIBUTING.md#installing-from-source).

My hope is that I get some time soon to tracedown the biggest issue I'm having and open a PR for the fix.

**Comment by bluedusk** [comment] 2015-04-09 13:29
0.7.4 not working, nothing shown with the tab, just blank

**Comment by vamsivarikuti** [comment] 2015-04-22 13:15
0.7.4 Not working, using batarang i got an error 'app not defined', please fix it. when i uninstall it my page is working fine.

**Comment by chino23** [comment] 2015-04-30 08:05
can't this at least be reverted to the last working version?

**Comment by SomeKittens** [comment] 2015-04-30 18:54
Closing this, as "not working" isn't terribly helpful and we don't need a general ticket for that.  It would be awesome if you guys could open new issues with your specific problems (as well as test cases for us to reproduce those issues).

**Closed by SomeKittens** 2015-04-30 18:54 UTC
